neighborhoods = [
    "Andersonville",
    "Archer Heights",
    "Ashburn",
    "Ashburn Estates",
    "Austin",
    "Avaondale",
    "Belmont Central",
    "Beverly",
    "Beverly Woods",
    "Brainerd",
    "Bridgeport",
    "Brighton Park",
    "Bronceville",
    "Bucktown",
    "Burnside",
    "Calumet Heights",
    "Canaryville",
    "Clearing",
    "Chatham",
    "Chinatown",
    "Cottage Grove Heights",
    "Cragin",
    "Dunning",
    "East Chicago",
    "Edison Park",
    "Edgebrook",
    "Edgewater",
    "Englewood",
    "Ford City",
    "Gage Park",
    "Galewood",
    "Garfield Park",
    "Garfield Ridge",
    "Gold Coast",
    "Grand Crossing",
    "Gresham",
    "Hamilton Park",
    "Humboldt Park",
    "Hyde Park",
    "Jefferson Park",
    "Kelvyn Park",
    "Kenwood",
    "Kilbourn Park",
    "Lake Meadows",
    "Lakeview",
    "Lawndale",
    "Lincoln Park",
    "Lincoln Square",
    "Little Village",
    "Logan Square",
    "Longwood Manor",
    "Loop",
    "Marquette Park",
    "McKinley Park",
    "Midway",
    "Morgan Park",
    "Montclare",
    "Mount Greenwood",
    "North Center",
    "Norwood Park",
    "Old Irving Park",
    "Old Town",
    "Park Manor",
    "Pilsen",
    "Princeton Park",
    "Portage Park",
    "Pullman",
    "Ravenswood",
    "River North",
    "River West",
    "Rodgers Park",
    "Roscoe VIllage",
    "Roseland",
    "Sauganash",
    "Schorsch Village",
    "Scottsdale",
    "South Chicago",
    "South Deering",
    "South Loop",
    "South Shore",
    "Streeterville",
    "Tri-Taylor",
    "Ukrainian Village",
    "United Center",
    "Uptown",
    "Vittum Park",
    "Washington Heights",
    "West Elsdon",
    "West Loop",
    "West Pullman",
    "Westlawn",
    "Wicker Park",
    "Woodlawn",
    "Wrigleyville",
    "Wrigtwood",
]
